-- ============================================================
-- Science Festivity 2026 -- corrected data migration
-- Generated from: PSC-ScienceFestivity2026(Leaflet)-V1.docx
-- Matches the schema in src/lib/types.ts (zones / booths /
-- booth_activities / event_info). Safe to re-run (idempotent).
-- ============================================================

begin;

-- 0) Schema guard -------------------------------------------
-- Creates the tables only if they don't already exist yet, matching
-- src/lib/types.ts exactly. If your `zones` / `booths` / `booth_activities`
-- / `event_info` tables already exist with different column names, DELETE
-- this block and just make sure the column names below line up.
create table if not exists public.zones (
  zone_id      bigint generated always as identity primary key,
  zone_code    text unique not null,
  name_ar      text not null,
  name_en      text not null
);

create table if not exists public.booths (
  booth_number integer primary key,
  zone_id      bigint references public.zones (zone_id)
);

create table if not exists public.booth_activities (
  activity_id       bigint generated always as identity primary key,
  booth_number      integer not null references public.booths (booth_number),
  institution_ar    text,
  institution_en    text,
  activity_type_ar  text,
  activity_type_en  text check (activity_type_en in ('Workshop','Presentation','Storytelling')),
  activity_dates    text,
  description_ar    text,
  description_en    text
);

create table if not exists public.event_info (
  info_key   text primary key,
  value_ar   text,
  value_en   text
);

-- 1) Zones (tents) -----------------------------------------
insert into public.zones (zone_code, name_ar, name_en) values ('gateway_to_universe', 'خيمة بوابة الكون', 'Gateway to the Universe Tent') on conflict (zone_code) do update set name_ar = excluded.name_ar, name_en = excluded.name_en;
insert into public.zones (zone_code, name_ar, name_en) values ('sky_observatory', 'خيمة مرصد السماء', 'Sky Observatory Tent') on conflict (zone_code) do update set name_ar = excluded.name_ar, name_en = excluded.name_en;
insert into public.zones (zone_code, name_ar, name_en) values ('big_bang', 'خيمة الانفجار العظيم', 'The Big Bang Tent') on conflict (zone_code) do update set name_ar = excluded.name_ar, name_en = excluded.name_en;
insert into public.zones (zone_code, name_ar, name_en) values ('planetarium_academy', 'خيمة أكاديمية القبة السماوية لتأهيل رواد الفضاء', 'Planetarium Academy for Astronaut Training Tent') on conflict (zone_code) do update set name_ar = excluded.name_ar, name_en = excluded.name_en;

-- 2) Booths ---------------------------------------------------
insert into public.booths (booth_number, zone_id) values (1, NULL) on conflict (booth_number) do update set zone_id = NULL;
insert into public.booths (booth_number, zone_id) select 2, zone_id from public.zones where zone_code = 'gateway_to_universe' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 3, zone_id from public.zones where zone_code = 'gateway_to_universe' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 4, zone_id from public.zones where zone_code = 'gateway_to_universe' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 5, zone_id from public.zones where zone_code = 'gateway_to_universe' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 6, zone_id from public.zones where zone_code = 'gateway_to_universe' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 7, zone_id from public.zones where zone_code = 'gateway_to_universe' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 8, zone_id from public.zones where zone_code = 'gateway_to_universe' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 9, zone_id from public.zones where zone_code = 'gateway_to_universe' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 10, zone_id from public.zones where zone_code = 'gateway_to_universe' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 11, zone_id from public.zones where zone_code = 'gateway_to_universe' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 12, zone_id from public.zones where zone_code = 'gateway_to_universe' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 13, zone_id from public.zones where zone_code = 'gateway_to_universe' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 14, zone_id from public.zones where zone_code = 'sky_observatory' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 15, zone_id from public.zones where zone_code = 'sky_observatory' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 16, zone_id from public.zones where zone_code = 'sky_observatory' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 17, zone_id from public.zones where zone_code = 'sky_observatory' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 18, zone_id from public.zones where zone_code = 'sky_observatory' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 19, zone_id from public.zones where zone_code = 'sky_observatory' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 20, zone_id from public.zones where zone_code = 'sky_observatory' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 21, zone_id from public.zones where zone_code = 'sky_observatory' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 22, zone_id from public.zones where zone_code = 'sky_observatory' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 23, zone_id from public.zones where zone_code = 'sky_observatory' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 24, zone_id from public.zones where zone_code = 'sky_observatory' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 25, zone_id from public.zones where zone_code = 'big_bang' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 26, zone_id from public.zones where zone_code = 'big_bang' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 27, zone_id from public.zones where zone_code = 'big_bang' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 28, zone_id from public.zones where zone_code = 'big_bang' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 29, zone_id from public.zones where zone_code = 'big_bang' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 30, zone_id from public.zones where zone_code = 'big_bang' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 31, zone_id from public.zones where zone_code = 'big_bang' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 32, zone_id from public.zones where zone_code = 'big_bang' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 33, zone_id from public.zones where zone_code = 'big_bang' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 34, zone_id from public.zones where zone_code = 'big_bang' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 35, zone_id from public.zones where zone_code = 'big_bang' on conflict (booth_number) do update set zone_id = excluded.zone_id;
insert into public.booths (booth_number, zone_id) select 36, zone_id from public.zones where zone_code = 'planetarium_academy' on conflict (booth_number) do update set zone_id = excluded.zone_id;

-- 3) Booth activities (institution + session per booth) -------
-- Wipe old activity rows for booths 1-36 so re-running this file
-- never produces duplicates, then insert the corrected set.
delete from public.booth_activities where booth_number between 1 and 36;

insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (1, 'الدعم الفني', NULL, NULL, NULL, NULL, NULL, NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (2, 'كلية التربية للطفولة المبكرة', NULL, 'ورشة عمل', 'Workshop', NULL, 'كيف يستكشف الإنسان الفضاء ويفهم عوالمه البعيدة؟ رحلة علمية تفاعلية يتعرف خلالها المشاركون إلى الأقمار الصناعية والتلسكوبات ومهام رواد الفضاء، ويستكشفون القمر والمريخ بأنفسهم من خلال نماذج وأنشطة عملية تحوّل استكشاف الفضاء إلى تجربة حية مليئة بالاكتشاف.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (3, 'جمعية المستقبل برج العرب', NULL, 'ورشة عمل', 'Workshop', NULL, 'إلى أي مدى يمكننا أن نرى في الكون؟ خض رحلة استكشافية تفاعلية تنطلق من الأرض وتعبر النظام الشمسي إلى النجوم والمجرات البعيدة، وصولًا إلى أعماق الثقوب السوداء، حيث تكشف التجارب والأنشطة البصرية كيف يمكن للإنسان أن يستكشف الكون ويتعرّف إلى تاريخه وحدوده.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (4, 'جمعية المستقبل برج العرب', NULL, 'ورشة عمل', 'Workshop', NULL, 'إلى أي مدى يمكننا أن نرى في الكون؟ خض رحلة استكشافية تفاعلية تنطلق من الأرض وتعبر النظام الشمسي إلى النجوم والمجرات البعيدة، وصولًا إلى أعماق الثقوب السوداء، حيث تكشف التجارب والأنشطة البصرية كيف يمكن للإنسان أن يستكشف الكون ويتعرّف إلى تاريخه وحدوده.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (5, 'المراكز الاستكشافية للعلوم والتكنولوجيا', NULL, 'ورشة عمل', 'Workshop', NULL, 'هل تعرف أن لكل كوكب خصائصه وأسراره التي تجعله عالمًا مختلفًا تمامًا؟ رحلة علمية تفاعلية نستكشف خلالها غرائب كواكب المجموعة الشمسية وأغرب العوالم المكتشفة خارجها، ونتعرف إلى أصواتها وخصائصها وشروط صلاحيتها للحياة، باستخدام التجارب والوسائط التفاعلية والواقع الافتراضي.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (6, 'كلية الفنون والتصميم،
الأكاديمية العربية للعلوم والتكنولوجيا والنقل البحري', NULL, 'عرض تقديمي', 'Presentation', NULL, 'ماذا لو اجتمعت شخصيات من حضارات مختلفة عبر الزمن لتكشف لنا أسرار النجوم؟ عرض فلكي مبتكر يجمع بين الحضارة والتاريخ والتكنولوجيا، من خلال «مجلس النجوم» الذي تلتقي فيه شخصيات مصرية ويونانية وعلماء ارتبطوا بتاريخ الفلك، في تجربة تجمع الدراما والذكاء الاصطناعي وتقنيات التقاط الحركة لاستكشاف كيف بدأ الإنسان رحلته لفهم السماء.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (7, 'كلية الفنون والتصميم،
الأكاديمية العربية للعلوم والتكنولوجيا والنقل البحري', NULL, 'عرض تقديمي', 'Presentation', NULL, 'ماذا لو اجتمعت شخصيات من حضارات مختلفة عبر الزمن لتكشف لنا أسرار النجوم؟ عرض فلكي مبتكر يجمع بين الحضارة والتاريخ والتكنولوجيا، من خلال «مجلس النجوم» الذي تلتقي فيه شخصيات مصرية ويونانية وعلماء ارتبطوا بتاريخ الفلك، في تجربة تجمع الدراما والذكاء الاصطناعي وتقنيات التقاط الحركة لاستكشاف كيف بدأ الإنسان رحلته لفهم السماء.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (8, 'كلية سان مارك', NULL, 'عرض تقديمي', 'Presentation', '26 سبتمبر', 'اشهدوا عجائب الضوء في ثلاثة عروض علمية متكاملة، حيث تتعرفون على سرّ الكسوف الشمسي وكيف تتشكل ظلال القمر، وتكتشفون كيف تتحول أشعة الشمس إلى كهرباء داخل الألواح الشمسية، وتشهدون كيف يجمع التلسكوب ملايين الفوتونات ليكشف أسرار الأجرام البعيدة. تجربة تفاعلية غنية تجمع بين التجارب العملية والنماذج، تفتح أعين المشاركين على قوة الضوء في فهم الكون وإنتاج الطاقة بطريقة شيقة وممتعة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (8, 'مكتبة الطفل، مكتبة الإسكندرية', NULL, 'ورشة عمل', 'Workshop', '28 و27 سبتمبر', 'عيشوا مغامرة فضائية ممتعة في «ورشة زحل في ورطة»، حيث تتعرفون على المجموعة الشمسية وحياة رواد الفضاء وإمكانية وجود كائنات خارج الأرض. ورشة تفاعلية مليئة بالمسرحية والفيديو والألعاب والنقاش، تفتح خيال أطفال المرحلة الابتدائية على أسرار الكون بطريقة شيقة ومشوقة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (9, 'أكاديمية ليتل إنجنير، دمنهور', NULL, 'ورشة عمل', 'Workshop', NULL, 'من القمر الذي نراه في سمائنا إلى الأقمار الصناعية التي تدور حول الأرض، اكتشف عالمًا كاملًا من الأجرام والتقنيات التي تغيّر حياتنا. تجربة علمية تفاعلية نتعرف خلالها إلى أسرار القمر وأطواره وأقماره المختلفة، ونكتشف كيف تعمل الأقمار الصناعية ونستخدمها في الملاحة والاتصالات، من خلال تحديات وتجارب عملية تضع المشاركين في قلب التجربة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (10, 'أكاديمية الترويح العلاجي والتعلم المرح', NULL, 'عرض تقديمي', 'Presentation', NULL, 'ماذا يوجد في عوالم النظام الشمسي العملاقة؟ تعرّف إلى المشتري وزحل وأورانوس ونبتون، واكتشف أسرار عمالقة الغاز والجليد من العواصف الهائلة والحلقات الغامضة إلى الظروف الجوية المتطرفة، في عرض تفاعلي يكشف تنوع أكثر الكواكب ضخامة في نظامنا الشمسي.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (11, 'المكتبات المتخصصة، مكتبة الإسكندرية', NULL, 'عرض تقديمي', 'Presentation', NULL, 'هل يمكن أن تتعلم عن الكواكب وأنت تلعب وتبني وتكتشف بنفسك؟ تعرّف إلى أسرار النظام الشمسي وحركة كواكبه وخصائصها من خلال تجربة تفاعلية تجمع بين الأنشطة العلمية والألعاب والتحديات، وتحول استكشاف الفضاء إلى مغامرة مليئة بالاكتشاف والمشاركة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (12, 'المكتبات المتخصصة، مكتبة الإسكندرية', NULL, 'عرض تقديمي', 'Presentation', NULL, 'هل يمكن أن تتعلم عن الكواكب وأنت تلعب وتبني وتكتشف بنفسك؟ تعرّف إلى أسرار النظام الشمسي وحركة كواكبه وخصائصها من خلال تجربة تفاعلية تجمع بين الأنشطة العلمية والألعاب والتحديات، وتحول استكشاف الفضاء إلى مغامرة مليئة بالاكتشاف والمشاركة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (13, 'كلية العلوم، جامعة الإسكندرية', NULL, 'عرض تقديمي', 'Presentation', NULL, 'من مراقبة الأرض من الفضاء إلى اكتشاف أسرار الكون، كيف غيّر استكشاف الفضاء حياتنا؟ رحلة علمية تفاعلية تكشف كيف تحوّلت الأقمار الصناعية والتلسكوبات من أدوات لاستكشاف المجهول إلى تقنيات أساسية نستخدمها كل يوم، وتدعونا إلى اكتشاف كيف يمكن لفضول الإنسان تجاه السماء أن يصنع تكنولوجيا تغيّر العالم.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (14, 'أسرة الصفوة، كلية العلوم، جامعة الإسكندرية', NULL, 'عرض تقديمي', 'Presentation', NULL, 'خطوة واحدة على القمر كانت بداية رحلة غيّرت تاريخ البشرية. تعرّف على أبرز مهمات استكشاف القمر والمريخ، واكتشف كيف انتقل الإنسان من الوصول إلى عوالم بعيدة إلى البحث عن أدلة على إمكانية وجود الحياة خارج الأرض.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (15, 'كلية طب الأسنان- جامعة الإسكندرية الأهلية', NULL, 'عرض تقديمي', 'Presentation', '26 سبتمبر', 'كيف نحافظ على صحة الإنسان عندما يصبح المستشفى على بُعد ملايين الكيلومترات؟ اكتشف كيف يواجه الطب تحديات الحياة في الفضاء، من تأثير انعدام الجاذبية على العظام والعضلات والدورة الدموية والأسنان، إلى توظيف الروبوتات والتقنيات المتقدمة في التشخيص والعلاج، لتمكين رواد الفضاء من الحفاظ على صحتهم بعيدًا عن الأرض.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (15, 'كلية التربية، جامعة الإسكندرية', NULL, 'عرض تقديمي', 'Presentation', '27 و28 سبتمبر', 'هل للنجوم عمرٌ ونهاية مثلنا؟ اكتشف رحلة النجم منذ ولادته داخل سحابة من الغاز والغبار، مرورًا بمراحل نضجه وشيخوخته، وصولًا إلى نهايته التي قد تصنع قزمًا أبيض أو نجمًا نيوترونيًا أو ثقبًا أسود، وتعرّف كيف تسهم النجوم في صناعة العناصر التي يتكوّن منها الكون والكواكب والحياة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (16, 'أسرة الصفوة، كلية التربية', NULL, 'عرض تقديمي', 'Presentation', NULL, 'ماذا لو لم تعد الأرض هي موطن البشرية الوحيد؟ انطلق في رحلة علمية تفاعلية من مغادرة الأرض والتغلب على جاذبيتها، إلى استكشاف الكواكب والسعي نحو الحياة خارجها، واكتشف التحديات العلمية والتكنولوجية التي تواجه حلم بناء مستقبل للبشرية خارج كوكبنا.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (17, 'فريق سنشيا', NULL, 'عرض تقديمي', 'Presentation', NULL, 'ماذا يحدث عندما يصل العلم إلى حدود معرفته؟ انطلق في رحلة إلى أعماق الثقوب السوداء، حيث تتحدى الجاذبية قوانين الزمكان، وتلتقي النسبية العامة بميكانيكا الكم، لنكتشف معًا كيف يحاول العلماء فك أحد أعقد ألغاز الكون والوصول إلى نظرية تفسّر أسرار الطبيعة بأكملها.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (18, 'فريق إنرجي فور مي (E4me)', NULL, 'عرض تقديمي', 'Presentation', NULL, 'انغمسوا في عوالم الأغلفة الجوية الغريبة لكواكب مجموعتنا الشمسية، من درع الأرض الحامي إلى أمطار الألماس على المشتري وزحل والرياح فوق الصوتية على نبتون. ورشة عمل حركية تفاعلية مليئة بالتحديات والألعاب، تنمي التفكير العلمي والوعي البيئي بأسلوب مرح وجاذب لا يُنسى.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (19, 'الفصل الطلابي للجمعية الأمريكية للكيمياء، جامعة الإسكندرية', NULL, 'عرض تقديمي', 'Presentation', NULL, 'ماذا لو استطاعت الكيمياء أن تكشف أسرار كوكب لم نكتشفه من قبل؟ انطلق في رحلة فلكية كيميائية بين نشأة الأنظمة الكوكبية والبراكين الفضائية والمواد الغريبة، واستخدم تجارب علمية تفاعلية لفك الإشارات الكيميائية والبحث عن أدلة على إمكانية وجود الحياة في عوالم بعيدة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (20, 'الاتحاد المصري لطلاب كلية الصيدلة بجامعة الإسكندرية', NULL, 'عرض تقديمي', 'Presentation', NULL, 'ماذا لو أصبح الفضاء مختبرًا لصناعة أدوية المستقبل؟ اكتشف كيف يستفيد العلماء من بيئة الفضاء الفريدة في دراسة بلورات البروتين وتطوير الأدوية باستخدام تقنيات متقدمة، مثل الطباعة ثلاثية الأبعاد، لفتح آفاق جديدة في الطب الشخصي والدواء الأكثر دقة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (21, 'مشروع ميكسولوجي', NULL, 'عرض تقديمي', 'Presentation', NULL, 'اكتشفوا أسرار الكون بأنفسكم في «بوابة النجوم»! تجربة علمية تفاعلية يتحول فيها المشاركون إلى محققي فضاء، يستكشفون ألغاز المادة المظلمة والثقوب السوداء والشفق القطبي والحياة خارج الأرض، ويستخدمون التجارب والأدلة العلمية لفهم ظواهر كونية ما زال بعضها يحير العلماء حتى اليوم..', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (22, 'فريق مركز التطوير الوظيفي وريادة الاعمال بكلية زراعة سابا باشا، جامعة الإسكندرية', NULL, 'عرض تقديمي', 'Presentation', NULL, 'كيف ساعدت النجوم المصريين القدماء على زراعة أرضهم وتنظيم حياتهم؟ رحلة علمية تكشف كيف ارتبطت مراقبة السماء بمواسم الفيضان والزراعة والحصاد في مصر القديمة، ثم تتيح للمشاركين تجربة زراعية عملية يستكشفون من خلالها كيف تحوّلت المعرفة الفلكية إلى أساس للحياة والزراعة منذ آلاف السنين.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (23, 'فريق سيڤ جونيور', NULL, 'عرض تقديمي', 'Presentation', NULL, 'كيف انتقل الإنسان من مجرد النظر إلى القمر إلى السير على سطحه، ثم البحث عن الحياة على المريخ؟ خُض مغامرة علمية عبر أهم محطات استكشاف القمر والمريخ، واكتشف قصصًا حقيقية من الشجاعة والابتكار تجاوزت حدود الأرض.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (24, 'أسرة طبيب من أجلك، كلية الطب، جامعة الإسكندرية', NULL, 'سرد قصصي', 'Storytelling', NULL, 'رحلة إلى الفضاء بحثًا عن الحياة! اكتشفوا كيف يقودنا علم الفلك والأحياء إلى أقمار جليدية بعيدة، وكائنات مجهرية خارقة، وأسرار قد تكشف لنا يومًا ما: هل توجد حياة خارج الأرض؟', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (25, 'مدرسة مجمع الشهداء الرسمية لغات', NULL, 'عرض تقديمي', 'Presentation', '26 سبتمبر', 'هل تستطيع أن تصبح عالمًا في مهمة لاستكشاف المريخ؟ خض رحلة تفاعلية إلى الكوكب الأحمر تتعرف خلالها إلى أبرز المهمات والمركبات التي استكشفت سطحه، ثم شارك بنفسك في محاكاة مهمة علمية للبحث عن عينات صخرية واكتشاف أسرار المريخ.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (25, 'مجمع مدارس خديجة بنت خويلد', NULL, 'عرض تقديمي', 'Presentation', '27 سبتمبر', 'انطلقوا في مغامرة تحقيقية علمية فريدة من نوعها، تكشفون خلالها سر الألوان الغامضة في السماء مع شخصيات ممتعة، لتتعرفوا على ظاهرة الشفق القطبي وكيف تتفاعل الجسيمات الشمسية مع غازات الغلاف الجوي لتنتج ألوانًا ساحرة. اكتشفوا أسرار الفضاء بطريقة تفاعلية مبهرة مستندة إلى مصادر علمية موثوقة، تغيّر نظرتكم إلى السماء إلى الأبد.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (25, 'مدرسة الشهيد ناصر محمد حسين الحكيم الابتدائية الرسمية', NULL, 'عرض تقديمي', 'Presentation', '28 سبتمبر', 'انطلقوا في رحلة علمية مدهشة تكشف سر ضوء النجوم والزمن الذي يستغرقه ليصل إلينا عبر الكون الشاسع، لتتعرفوا على وحدات القياس الفلكية مثل السنة الضوئية والوحدة الفلكية، وتدركوا كيف نرى النجوم كما كانت في الماضي. نشاط تفاعلي فريد يجمع بين الشرح والنماذج والمسابقات، يفتح أعينكم على عظمة الفضاء بطريقة مبسطة وممتعة تغيّر نظرتكم إلى السماء إلى الأبد.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (26, 'مدرسة قصر رأس التين الابتدائية', NULL, 'عرض تقديمي', 'Presentation', '26 سبتمبر', 'استكشفوا عالم الكواكب الثمانية في مجموعتنا الشمسية، من عطارد الصخري الحار إلى نبتون الجليدي البعيد، لتتعرفوا على اختلافاتها في الحجم والكتلة والحرارة والأقمار والألوان، واكتشفوا أغرب الحقائق العلمية عنها. عرض تفاعلي ممتع يبسط أسرار الجيران الكونيين بطريقة شيقة تفتح آفاق الطلاب على عظمة النظام الشمسي.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (26, 'مدرسة نبوية موسي الإعدادية النموذجية بنات', NULL, 'عرض تقديمي', 'Presentation', '27 و28سبتمبر', 'انطلقوا في رحلة تفاعلية مدهشة عبر عائلة الكواكب الغريبة في مجموعتنا الشمسية، من عطارد المتقلب إلى نبتون ذي الرياح الهائلة، لتكتشفوا خصائصها العجيبة وأسرارها العلمية بطريقة حية وممتعة. نشاط فريد يجمع بين المعرفة الدقيقة المستمدة من ناسا والتأمل في تميز كوكبنا الأرض، يفتح أعينكم على عظمة الكون ويدعوكم إلى حمايته.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (27, 'مدرسة الأنفوشي', NULL, 'ورشة عمل', 'Workshop', '26 سبتمبر', 'انطلقوا في رحلة استكشافية ممتعة إلى عالم القمر، لتكتشفوا كيف يدور حول الأرض في مداره العجيب، ولماذا تتغير أطواره الثمانية كل شهر، وسرّ رؤيتنا لوجه واحد منه دائمًا. نشاط علمي مبسط وشيق يفتح أعين أطفال المرحلة الابتدائية على أسرار الفضاء بطريقة تفاعلية رائعة تزرع حب الاستكشاف في نفوسهم.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (27, 'مدرسة فاطمة الزهراء الرسمية لغات', NULL, 'عرض تقديمي', 'Presentation', '27 سبتمبر', 'اطلعوا على أسرار مجموعتنا الشمسية وأطوار القمر بطريقة ممتعة ومبسطة، حيث تتعرفون على الكواكب وأسماءها وأشكال القمر المتغيرة كل شهر. نشاط تفاعلي يعتمد على النموذج والمسابقة، يفتح أعين أطفال المرحلة الابتدائية على عالم الفضاء بأسلوب شيق وجذاب.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (27, 'مجمع مدارس اللواء محمد نجيب الرسمية لغات', NULL, 'ورشة عمل', 'Workshop', '28 سبتمبر', 'اكتشفوا أسرار نشأة الكون في عرض علمي استثنائي يستكشف نظرية الانفجار العظيم، وكيف بدأ الكون منذ 13.8 مليار سنة وتطور عبر مراحله المدهشة من التضخم الكوني حتى تشكل المجرات والنجوم. تجربة تفاعلية فريدة تجمع بين فيديو مولّد بالذكاء الاصطناعي ولوحة عرض حية ومسابقات، تفتح آفاق الأجيال على عظمة الكون بطريقة شيقة وممتعة لا تُنسى.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (28, 'مدرسة سيتي الدولية', NULL, 'عرض تقديمي', 'Presentation', NULL, 'هل نحن وحدنا في هذا الكون الواسع؟ يكشف هذا العرض العلمي أسرار البحث عن الحياة خارج الأرض من خلال علم الأحياء الفلكي، وشروط الوجود، والأماكن الواعدة مثل المريخ وأوروبا، وكيفية بحث العلماء عنها بالتقنيات الحديثة. تجربة تفاعلية ممتعة تجمع بين الشرح والنماذج والألعاب، تفتح آفاق المشاركين على أحد أعظم ألغاز الكون بطريقة شيقة ومبسطة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (29, 'مدرسة القادسية الخاصة', NULL, 'ورشة عمل', 'Workshop', '28 سبتمبر', 'اكتشفوا أسرار الرصد الفلكي في نشاط علمي مبسط، حيث تتعرفون على أنواع التلسكوبات والأجهزة التي مكنت العلماء من كشف خفايا النجوم والكواكب والمجرات. تجربة تفاعلية تجمع بين النماذج والصور والمناقشة، تفتح أعين المشاركين على دور التكنولوجيا في فهم الكون بطريقة شيقة وممتعة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (30, 'مدرسة فيكتوريا', NULL, 'عرض تقديمي', 'Presentation', NULL, 'تابعوا مسيرة رواد الفضاء عبر التاريخ في أنشطة تفاعلية ممتعة، حيث تتعرفون على أبرز الشخصيات والرحلات والإنجازات من يوري جاجارين إلى الرواد العرب المعاصرين. تجربة تعليمية شيقة تجمع بين الصور والكروت والخط الزمني، تغرس حب الفضاء والاكتشاف في نفوس طلاب المرحلة الابتدائية بطريقة جذابة ومبسطة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (31, 'المدرسة المصرية اليابانية، فرع المنتزه، المرحلة الإعدادية', NULL, 'عرض تقديمي', 'Presentation', NULL, 'انضموا إلى مهمة فضائية تفاعلية لفك شفرة رسالة غامضة قادمة من نجم بعيد، حيث تتعرفون عبر خمس محطات شيقة على كيف يقرأ العلماء أسرار الكون من خلال الضوء وحده. تجربة ممتعة تحول المشاركين إلى محققي فضاء، وتكشف لهم أن النظر إلى السماء هو في الحقيقة نظرة إلى الماضي بطريقة علمية جذابة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (32, 'كلية سان مارك', NULL, 'عرض تقديمي', 'Presentation', NULL, 'اشهدوا عجائب الضوء في ثلاثة عروض علمية متكاملة، حيث تتعرفون على سرّ الكسوف الشمسي وكيف تتشكل ظلال القمر، وتكتشفون كيف تتحول أشعة الشمس إلى كهرباء داخل الألواح الشمسية، وتشهدون كيف يجمع التلسكوب ملايين الفوتونات ليكشف أسرار الأجرام البعيدة. تجربة تفاعلية غنية تجمع بين التجارب العملية والنماذج، تفتح أعين المشاركين على قوة الضوء في فهم الكون وإنتاج الطاقة بطريقة شيقة وممتعة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (33, 'مدرسة اسكندرية للغات STEAM', NULL, 'عرض تقديمي', 'Presentation', '26 سبتمبر', 'الإدريسي وإنجازه الكبير في رسم خريطة العالم بدقة.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (33, 'مدرسة كلية الإقبال القومية، السرايا', NULL, 'عرض تقديمي', 'Presentation', '27 سبتمبر', 'كيف يستطيع العلماء معرفة أسرار نجم يبعد عنا ملايين السنين الضوئية دون أن يلمسوه؟ رحلة علمية تكشف كيف يتحول الضوء إلى لغة يقرأ بها العلماء تركيب النجوم وحركتها وتاريخ الكون، وصولًا إلى استخدام البصمات الحيوية للبحث عن عوالم قد تحمل مقومات الحياة خارج الأرض..', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (33, 'مدرسة الزهراء الدولية، قسم الnational', NULL, 'عرض تقديمي', 'Presentation', '28 سبتمبر', 'اكتشفوا عالم النجوم المتنوع في مسرحية تفاعلية شيقة، حيث تتعرفون على ألوانها وأحجامها وأعمارها المختلفة، وتتبعون رحلة حياتها من الولادة داخل السديم حتى نهاياتها المذهلة. تجربة علمية ممتعة تجمع بين التمثيل والمسابقات، تزرع حب الفلك في نفوس الأطفال وتفتح أعينهم على أسرار الكون بطريقة لا تُنسى.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (34, 'مدرسة اسكندرية للغات', NULL, 'عرض تقديمي', 'Presentation', NULL, 'تعرّفوا على كيفية بناء مستوطنة بشرية مستدامة على سطح المريخ من خلال نموذج عملي مبتكر، يشمل صوبة زراعية محمية وألواحًا شمسية وأنظمة مراقبة ذكية لمواجهة تحديات الكوكب الأحمر. عرض تفاعلي قصير يجمع بين الشرح العملي والمسابقة، يلهم المشاركين بأفكار التكنولوجيا الفضائية المستقبلية.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (35, 'فريق عقول المستقبل', NULL, 'عرض تقديمي', 'Presentation', NULL, 'اكتشفوا رحلة كونية فريدة لم يسبق لها مثيل: من ولادة النجوم داخل السُدُم حتى نهايتها في انفجارات المستعرات العظمى، لتتعرفوا على كيف تصنع النجوم العناصر التي تكوّن الكواكب والحياة نفسها، وتفهموا أسرار الكون بطريقة علمية مبهرة تغيّر نظرتكم إلى السماء إلى الأبد.', NULL);
insert into public.booth_activities (booth_number, institution_ar, institution_en, activity_type_ar, activity_type_en, activity_dates, description_ar, description_en) values (36, 'مركز القبة السماوية العلمي', NULL, 'ورشة عمل', 'Workshop', NULL, 'انطلقوا في مهمة تدريبية واستكشافية مثيرة تصبحون فيها رواد فضاء حقيقيين، تتدربون جسديًا ونفسيًا وعلميًا قبل الإبحار في رحلة افتراضية إلى كوكب خارج المجموعة الشمسية. ورشة تفاعلية غامرة مدتها 45 دقيقة تجمع بين التدريب العملي والسفر الخيالي، تزرع حب الاستكشاف في نفوس الأطفال بطريقة لا تُنسى.', NULL);

-- 4) Event-wide info (for the About tab) -----------------------
insert into public.event_info (info_key, value_ar, value_en) values ('event_name_ar', 'احتفالية العلوم 2026', 'Science Festivity 2026') on conflict (info_key) do update set value_ar = excluded.value_ar, value_en = excluded.value_en;
insert into public.event_info (info_key, value_ar, value_en) values ('tagline_ar', 'أبدأ رحلة الاكتشاف، الكون أقرب مما تظن', 'Start the Adventure — The Universe Is Closer Than You Think') on conflict (info_key) do update set value_ar = excluded.value_ar, value_en = excluded.value_en;
insert into public.event_info (info_key, value_ar, value_en) values ('dates_ar', 'من السبت إلى الاثنين، 26–28 سبتمبر 2026', 'Saturday to Monday, 26–28 September 2026') on conflict (info_key) do update set value_ar = excluded.value_ar, value_en = excluded.value_en;
insert into public.event_info (info_key, value_ar, value_en) values ('hours_ar', '9:00 صباحًا – 2:00 ظهرًا', '9:00 am – 2:00 pm') on conflict (info_key) do update set value_ar = excluded.value_ar, value_en = excluded.value_en;
insert into public.event_info (info_key, value_ar, value_en) values ('venue_ar', 'مكتبة الإسكندرية، الساحة الخارجية (البلازا)', 'Bibliotheca Alexandrina, Plaza') on conflict (info_key) do update set value_ar = excluded.value_ar, value_en = excluded.value_en;
insert into public.event_info (info_key, value_ar, value_en) values ('target_audience_ar', 'رياض أطفال، المرحلة الابتدائية، المرحلة الإعدادية، المرحلة الثانوية والجامعية، ذوي الهمم', 'Kindergarten, Primary, Preparatory, Secondary & University, People of Determination') on conflict (info_key) do update set value_ar = excluded.value_ar, value_en = excluded.value_en;


-- 5) Floor-plan correction -------------------------------------
-- The physical floor plan changed after this file was first written:
-- booth 13 moved from "بوابة الكون" into "مرصد السماء", and booths 11 & 12
-- no longer exist anywhere in the venue (no space for them in the new
-- layout). This block runs AFTER the inserts above on purpose, so it always
-- wins and leaves the data in the correct final state no matter how many
-- times this file is re-run.
update public.booths
set zone_id = (select zone_id from public.zones where zone_code = 'sky_observatory')
where booth_number = 13;

delete from public.booth_activities where booth_number in (11, 12);
delete from public.booths where booth_number in (11, 12);

commit;
